### ISSUE TITLE
no extra girls

### ISSUE THREAD

**Issue by morphette** [Mantas-2155X/AI_ExtraGirls#10]
hi i have tried using the extra girls but nothing happens. i am in freemode and not using steam.

the log has this in it
[Info   :   BepInEx] Loading [AI_ExtraGirls 1.0.3]
[Message:AI_ExtraGirls] Failed transpiling 'MapUIContainer_GetActorColor_RemoveActorColorCheckError' LogError index not found!
[Warning:AI_ExtraGirls] Failed transpiling 'MapUIContainer_GetActorColor_RemoveActorColorCheckError' LogError index not found!

please help

**Comment by Mantas-2155X** [comment]
Please try this build and tell me if the problems still happen. Also, make sure your game is up to date.
[AI_ExtraGirls.zip](https://github.com/Mantas-2155X/AI_ExtraGirls/files/5469651/AI_ExtraGirls.zip)

**Comment by morphette** [comment]
it worked. thank you so much for your help.

**Comment by Mantas-2155X** [comment]
thank you for reporting the issue :)
