### ISSUE TITLE
Slow speed when using mod

### ISSUE THREAD

**Issue by Jooris1** [Mantas-2155X/AI_ExtraGirls#11]
What is the soft limit for using this mod? How to improve performance?

**Comment by Mantas-2155X** [comment]
Already answered in DM, but for those who are wondering, there isn't really a way to improve performance for this unfortunately, but you can try this:
4GB VRAM - 4-5 girls
6GB VRAM - 5-7 girls
8GB VRAM - 7-9 girls

Also, setting the render res to 1/4 drops the map quality and should decrease the VRAM usage by quite a bit.
