### ISSUE TITLE
New addition can't take off clothes in H mode

### ISSUE THREAD

**Issue by qq564522482** [Mantas-2155X/AI_ExtraGirls#2]

**Comment by qq564522482** [comment]
New addition can't take off clothes in H mode

**Comment by Mantas-2155X** [comment]
This plugin does not interfere with anything related to H scenes or clothes. 
Please make sure you're making the issue for the correct plugin.

Also, next time please include more information like, is this caused by an update, if so from which version, how to reproduce the error.. etc.
