### ISSUE TITLE
Hello, author. this question about After adding femen

### ISSUE THREAD

**Issue by qq564522482** [Mantas-2155X/AI_ExtraGirls#3]
The game new version is 1.0.6， After using ExtraGirls.dll ,Added women cannot undress in H mode，  But the four in the game can be undressed

**Comment by qq564522482** [comment]
I found the problem. If there are more than seven people, this bug will appear

**Comment by Mantas-2155X** [comment]
Hello again.
I have added 10 extra girls and I am still able to take off their clothes during H. 
Please make sure you are not having conflicting plugins. 
Also, please post your "output_log.txt" file from your game directory. It can be uploaded to www.pastebin.com and linked here

**Comment by Mantas-2155X** [comment]
Closed due to no reply
