### ISSUE TITLE
ai Extra girls 

### ISSUE THREAD

**Issue by yosimitysam93** [Mantas-2155X/AI_ExtraGirls#4]
I installed as read me said does not work

**Comment by Mantas-2155X** [comment]
Hello,

Do you have the `AI_ExtraGirls.dll` file in `BepInEx/plugins/2155X/` folder?
If not, you installed it incorrectly.

Also, if possible please send your output_log.txt file from your game directory

**Comment by yosimitysam93** [comment]
I figured it out. The game wasn't registering as restarting. The task wasn't ending, just suspending itself to the background processes in my computer. thanks for the quick reply though.
