### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by darkdaz1** [Mantas-2155X/AI_ExtraGirls#5]
In your "Configuration:" header, you say there is a config file, but I am seeing no config files installed after launch. The BepinEx configuration manager also does not see any configurations for the mod. Where would i find this?

**Comment by Mantas-2155X** [comment]
Hello,

The configuration is done within the game. If you have the latest BepInEx and ConfigurationManager, you should see a button called "Plugin Settings" in your games settings. Clicking it should open a menu and configuration should be located under the "AI_ExtraGirls" category.

If any of those steps don't exist or don't work, please make sure your BepInEx and ConfigurationManager are up to date.

**Comment by Mantas-2155X** [comment]
No reply in 5 days, closed
