### ISSUE TITLE
Cant strip added Girls on H scene

### ISSUE THREAD

**Issue by TTVBanshee** [Mantas-2155X/AI_ExtraGirls#6]
Hello, dont know if this is only my problem or some common problem, but Girls who went over the Limit of 4 are unstrippable in H Scenes. I have installed the Full-Repack where your Mod is uncluded if this could help solve it.

**Comment by Mantas-2155X** [comment]
Hello,
I just tried H scene with a girl in slot 6, I was able to take off/put on her clothes by using the default game UI. 

- How are you stripping the girls, are you doing it through some custom plugins?  
- Have you installed any new plugins outside of the ones, which come with the repack?
- Is the game full repack BetterRepack?

**Comment by TTVBanshee** [comment]
Ok, i tested it with a new, clean install o Pack 4.1 and it works fine. Maybe i had an unclean and messed up Version bcs i had the orginal before. Thanks a lot for your Hint and thanks for this absolute awesome Mod!

**Comment by Mantas-2155X** [comment]
I'm glad everything is fine. 
If the issue comes up again, please open a new ticket with as much information as possible, like what was the last mod/plugin you installed and any steps to re-create the bug.

Closed~
