### ISSUE TITLE
extra girls missing some  characteristic

### ISSUE THREAD

**Issue by assidence** [Mantas-2155X/AI_ExtraGirls#7]
Hello, I have using the plugin generate 5 extra girls, I realize that the girls were missing emotion ,excited level and won't get new special point.

**Comment by Mantas-2155X** [comment]
Hello,
Please explain more about what you mean. Give pictures, output_log.txt or anything that can point me to what's missing.

**Comment by assidence** [comment]
hello, I have mark the missing function
![Annotation 2020-07-13 101519](https://user-images.githubusercontent.com/15117775/87264359-5f67f680-c4f2-11ea-9ed8-b57812ee38be.png)
![Annotation 2020-07-13 101557](https://user-images.githubusercontent.com/15117775/87264365-61ca5080-c4f2-11ea-8887-f79ec6316144.png)

**Comment by Mantas-2155X** [comment]
I will need to do some more testing and hopefully get to this when I have more time

**Comment by Bluefang165** [comment]
Not sure if this helps but the reason why you cannot see those stats is that you only have 2 hearts you need 3 to see them as this is part of the core mechanic of the game.

**Comment by Mantas-2155X** [comment]
Thank you, Bluefang165 for an explanation.

Invalid issue, closed.
