### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by vadrien1999** [Mantas-2155X/AI_ExtraGirls#9]
Hello, I put in extra girls 9 girls as the number, I restarted and I was on several different terminals but I cannot add girls, the option does not appear. I have version 1.1.1 of the game and betterrepack 6.1

**Comment by Mantas-2155X** [comment]
Hello, increasing extra girls does not unlock vanilla girls. There are 4 first slots which are all vanilla and unlocked by your save. To access the extra girls, you need to scroll down in the UI and they should be accessible.

**Comment by Mantas-2155X** [comment]
No reply, closed
